### PR TITLE
Complete refactor, especially of command systems

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by RyanHir** [comment]
Made some fixes to merge master changes back into this branch, it should compile fine but we should test the changes on the robot when we get back from the extended break. I do not think we should merge until then.

**Comment by democat3457** [comment]
> we should test the changes on the robot when we get back from the extended break

**Comment by RyanHir** [comment]
Lol

**Comment by RyanHir** [comment]
Ok. if things break, we roll back. We will probably not have the robot for another few months.

**Pull request merged**
